// Code generated by mockery v1.0.0. DO NOT EDIT.

package httpmock

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// Handler is an autogenerated mock type for the Handler type
type Handler struct {
	mock.Mock
}

// ServeHTTP provides a mock function with given fields: writer, request
func (_m *Handler) ServeHTTP(writer http.ResponseWriter, request *http.Request) {
	_m.Called(writer, request)
}
