// Code generated by mockery v1.0.0. DO NOT EDIT.

package data

import (
	context "context"

	openapi3 "github.com/getkin/kin-openapi/openapi3"
	mock "github.com/stretchr/testify/mock"
)

// mockSchemaGenerator is an autogenerated mock type for the schemaGenerator type
type mockSchemaGenerator struct {
	mock.Mock
}

// GenerateDataBySchema provides a mock function with given fields: ctx, schema
func (_m *mockSchemaGenerator) GenerateDataBySchema(ctx context.Context, schema *openapi3.Schema) (Data, error) {
	ret := _m.Called(ctx, schema)

	var r0 Data
	if rf, ok := ret.Get(0).(func(context.Context, *openapi3.Schema) Data); ok {
		r0 = rf(ctx, schema)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Data)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *openapi3.Schema) error); ok {
		r1 = rf(ctx, schema)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
