// Code generated by mockery v1.0.0. DO NOT EDIT.

package generator

import (
	openapi3 "github.com/getkin/kin-openapi/openapi3"
	mock "github.com/stretchr/testify/mock"
)

// mockSchemaGenerator is an autogenerated mock type for the schemaGenerator type
type mockSchemaGenerator struct {
	mock.Mock
}

// GenerateDataBySchema provides a mock function with given fields: schema
func (_m *mockSchemaGenerator) GenerateDataBySchema(schema *openapi3.Schema) (Data, error) {
	ret := _m.Called(schema)

	var r0 Data
	if rf, ok := ret.Get(0).(func(*openapi3.Schema) Data); ok {
		r0 = rf(schema)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Data)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*openapi3.Schema) error); ok {
		r1 = rf(schema)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
