// Code generated by mockery v1.0.0. DO NOT EDIT.

package generator

import mock "github.com/stretchr/testify/mock"

// mockRandomGenerator is an autogenerated mock type for the randomGenerator type
type mockRandomGenerator struct {
	mock.Mock
}

// Float64 provides a mock function with given fields:
func (_m *mockRandomGenerator) Float64() float64 {
	ret := _m.Called()

	var r0 float64
	if rf, ok := ret.Get(0).(func() float64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(float64)
	}

	return r0
}
