<?php
/*
 * This file is part of Swagger Mock.
 *
 * (c) Igor Lazarev <strider2038@yandex.ru>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Mock\Generation;

use App\Mock\Parameters\Schema\Schema;
use Psr\Log\LoggerInterface;

/**
 * @author Igor Lazarev <strider2038@yandex.ru>
 */
class DataGenerator
{
    /** @var ValueGeneratorLocator */
    private $generatorLocator;

    /** @var LoggerInterface */
    private $logger;

    public function __construct(ValueGeneratorLocator $generatorLocator, LoggerInterface $logger)
    {
        $this->generatorLocator = $generatorLocator;
        $this->logger = $logger;
    }

    public function generateData(Schema $schema)
    {
        $valueGenerator = $this->generatorLocator->getValueGenerator($schema->value);
        $data = $valueGenerator->generateValue($schema->value);

        $this->logger->info(
            sprintf(
                'Response data for scheme "%s" was successfully generated by "%s".',
                \get_class($schema->value),
                \get_class($valueGenerator)
            )
        );

        return $data;
    }
}
