// Code generated by mockery v1.0.0. DO NOT EDIT.

package contentmock

import (
	context "context"

	openapi3 "github.com/getkin/kin-openapi/openapi3"
	mock "github.com/stretchr/testify/mock"
)

// Generator is an autogenerated mock type for the Generator type
type Generator struct {
	mock.Mock
}

// GenerateContent provides a mock function with given fields: ctx, response, contentType
func (_m *Generator) GenerateContent(ctx context.Context, response *openapi3.Response, contentType string) (interface{}, error) {
	ret := _m.Called(ctx, response, contentType)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(context.Context, *openapi3.Response, string) interface{}); ok {
		r0 = rf(ctx, response, contentType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *openapi3.Response, string) error); ok {
		r1 = rf(ctx, response, contentType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
