// Code generated by mockery v1.0.0. DO NOT EDIT.

package data

import (
	openapi3 "github.com/getkin/kin-openapi/openapi3"
	mock "github.com/stretchr/testify/mock"
)

// mockSchemaMerger is an autogenerated mock type for the schemaMerger type
type mockSchemaMerger struct {
	mock.Mock
}

// MergeSchemas provides a mock function with given fields: schema
func (_m *mockSchemaMerger) MergeSchemas(schema *openapi3.Schema) *openapi3.Schema {
	ret := _m.Called(schema)

	var r0 *openapi3.Schema
	if rf, ok := ret.Get(0).(func(*openapi3.Schema) *openapi3.Schema); ok {
		r0 = rf(schema)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*openapi3.Schema)
		}
	}

	return r0
}
