// Code generated by mockery v1.0.0. DO NOT EDIT.

package data

import mock "github.com/stretchr/testify/mock"

// mockRandomGenerator is an autogenerated mock type for the randomGenerator type
type mockRandomGenerator struct {
	mock.Mock
}

// Float64 provides a mock function with given fields:
func (_m *mockRandomGenerator) Float64() float64 {
	ret := _m.Called()

	var r0 float64
	if rf, ok := ret.Get(0).(func() float64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(float64)
	}

	return r0
}

// Int63n provides a mock function with given fields: n
func (_m *mockRandomGenerator) Int63n(n int64) int64 {
	ret := _m.Called(n)

	var r0 int64
	if rf, ok := ret.Get(0).(func(int64) int64); ok {
		r0 = rf(n)
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// Intn provides a mock function with given fields: n
func (_m *mockRandomGenerator) Intn(n int) int {
	ret := _m.Called(n)

	var r0 int
	if rf, ok := ret.Get(0).(func(int) int); ok {
		r0 = rf(n)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}
