// Code generated by mockery v1.0.0. DO NOT EDIT.

package loader

import (
	openapi3 "github.com/getkin/kin-openapi/openapi3"
	mock "github.com/stretchr/testify/mock"
)

// MockSpecificationLoader is an autogenerated mock type for the SpecificationLoader type
type MockSpecificationLoader struct {
	mock.Mock
}

// LoadFromURI provides a mock function with given fields: uri
func (_m *MockSpecificationLoader) LoadFromURI(uri string) (*openapi3.Swagger, error) {
	ret := _m.Called(uri)

	var r0 *openapi3.Swagger
	if rf, ok := ret.Get(0).(func(string) *openapi3.Swagger); ok {
		r0 = rf(uri)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*openapi3.Swagger)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(uri)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
