// Code generated by mockery v1.0.0. DO NOT EDIT.

package negotiatormock

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"

	openapi3 "github.com/getkin/kin-openapi/openapi3"
)

// ContentTypeNegotiator is an autogenerated mock type for the ContentTypeNegotiator type
type ContentTypeNegotiator struct {
	mock.Mock
}

// NegotiateContentType provides a mock function with given fields: request, response
func (_m *ContentTypeNegotiator) NegotiateContentType(request *http.Request, response *openapi3.Response) string {
	ret := _m.Called(request, response)

	var r0 string
	if rf, ok := ret.Get(0).(func(*http.Request, *openapi3.Response) string); ok {
		r0 = rf(request, response)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
