// Code generated by mockery v1.0.0. DO NOT EDIT.

package negotiatormock

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"

	openapi3 "github.com/getkin/kin-openapi/openapi3"
)

// StatusCodeNegotiator is an autogenerated mock type for the StatusCodeNegotiator type
type StatusCodeNegotiator struct {
	mock.Mock
}

// NegotiateStatusCode provides a mock function with given fields: request, responses
func (_m *StatusCodeNegotiator) NegotiateStatusCode(request *http.Request, responses openapi3.Responses) (string, int, error) {
	ret := _m.Called(request, responses)

	var r0 string
	if rf, ok := ret.Get(0).(func(*http.Request, openapi3.Responses) string); ok {
		r0 = rf(request, responses)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(*http.Request, openapi3.Responses) int); ok {
		r1 = rf(request, responses)
	} else {
		r1 = ret.Get(1).(int)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(*http.Request, openapi3.Responses) error); ok {
		r2 = rf(request, responses)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
