@startuml

RequestHandler -> MockRepository : findMockEndpoint(httpMethod, uri)
RequestHandler <- MockRepository : mockEndpoint
RequestHandler -> MockResponseGenerator : generateResponse(request, mockEndpoint)
MockResponseGenerator -> MediaTypeNegotiator : negotiateMediaType(request, mockEndpoint)
MockResponseGenerator <- MediaTypeNegotiator : mediaType
MockResponseGenerator -> ResponseStatusNegotiator : negotiateResponseStatus(request, mockEndpoint)
MockResponseGenerator <- ResponseStatusNegotiator : statusCode
MockResponseGenerator -> DataGenerator : generateResponseData(schema)
MockResponseGenerator <- DataGenerator : data
MockResponseGenerator -> Responder : createResponse(statusCode, mediaType, data)
MockResponseGenerator <- Responder : response
RequestHandler <- MockResponseGenerator : response

@enduml
